//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 VMware Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package resources

import (
	"dies.dev/apis/meta/v1"
	json "encoding/json"
	fmtx "fmt"
	meta "github.com/fluxcd/pkg/apis/meta"
	"github.com/garethjevans/filter-controller/api/v1alpha1"
	apis "github.com/vmware-labs/reconciler-runtime/apis"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	jsonpath "k8s.io/client-go/util/jsonpath"
	osx "os"
	reflectx "reflect"
	yaml "sigs.k8s.io/yaml"
)

var FilteredRepositoryBlank = (&FilteredRepositoryDie{}).DieFeed(v1alpha1.FilteredRepository{})

type FilteredRepositoryDie struct {
	v1.FrozenObjectMeta
	mutable bool
	r       v1alpha1.FilteredRepository
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *FilteredRepositoryDie) DieImmutable(immutable bool) *FilteredRepositoryDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *FilteredRepositoryDie) DieFeed(r v1alpha1.FilteredRepository) *FilteredRepositoryDie {
	if d.mutable {
		d.FrozenObjectMeta = v1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &FilteredRepositoryDie{
		FrozenObjectMeta: v1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *FilteredRepositoryDie) DieFeedPtr(r *v1alpha1.FilteredRepository) *FilteredRepositoryDie {
	if r == nil {
		r = &v1alpha1.FilteredRepository{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *FilteredRepositoryDie) DieFeedJSON(j []byte) *FilteredRepositoryDie {
	r := v1alpha1.FilteredRepository{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *FilteredRepositoryDie) DieFeedYAML(y []byte) *FilteredRepositoryDie {
	r := v1alpha1.FilteredRepository{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *FilteredRepositoryDie) DieFeedYAMLFile(name string) *FilteredRepositoryDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *FilteredRepositoryDie) DieFeedRawExtension(raw runtime.RawExtension) *FilteredRepositoryDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *FilteredRepositoryDie) DieRelease() v1alpha1.FilteredRepository {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *FilteredRepositoryDie) DieReleasePtr() *v1alpha1.FilteredRepository {
	r := d.DieRelease()
	return &r
}

// DieReleaseUnstructured returns the resource managed by the die as an unstructured object. Panics on error.
func (d *FilteredRepositoryDie) DieReleaseUnstructured() *unstructured.Unstructured {
	r := d.DieReleasePtr()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(r)
	if err != nil {
		panic(err)
	}
	return &unstructured.Unstructured{
		Object: u,
	}
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *FilteredRepositoryDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *FilteredRepositoryDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *FilteredRepositoryDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *FilteredRepositoryDie) DieStamp(fn func(r *v1alpha1.FilteredRepository)) *FilteredRepositoryDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *FilteredRepositoryDie) DieStampAt(jp string, fn interface{}) *FilteredRepositoryDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepository) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *FilteredRepositoryDie) DeepCopy() *FilteredRepositoryDie {
	r := *d.r.DeepCopy()
	return &FilteredRepositoryDie{
		FrozenObjectMeta: v1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

var _ runtime.Object = (*FilteredRepositoryDie)(nil)

func (d *FilteredRepositoryDie) DeepCopyObject() runtime.Object {
	return d.r.DeepCopy()
}

func (d *FilteredRepositoryDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *FilteredRepositoryDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *FilteredRepositoryDie) UnmarshalJSON(b []byte) error {
	if d == FilteredRepositoryBlank {
		return fmtx.Errorf("cannot unmarshal into the blank die, create a copy first")
	}
	if !d.mutable {
		return fmtx.Errorf("cannot unmarshal into immutable dies, create a mutable version first")
	}
	r := &v1alpha1.FilteredRepository{}
	err := json.Unmarshal(b, r)
	*d = *d.DieFeed(*r)
	return err
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (d *FilteredRepositoryDie) APIVersion(v string) *FilteredRepositoryDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepository) {
		r.APIVersion = v
	})
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (d *FilteredRepositoryDie) Kind(v string) *FilteredRepositoryDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepository) {
		r.Kind = v
	})
}

// MetadataDie stamps the resource's ObjectMeta field with a mutable die.
func (d *FilteredRepositoryDie) MetadataDie(fn func(d *v1.ObjectMetaDie)) *FilteredRepositoryDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepository) {
		d := v1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

// SpecDie stamps the resource's spec field with a mutable die.
func (d *FilteredRepositoryDie) SpecDie(fn func(d *FilteredRepositorySpecDie)) *FilteredRepositoryDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepository) {
		d := FilteredRepositorySpecBlank.DieImmutable(false).DieFeed(r.Spec)
		fn(d)
		r.Spec = d.DieRelease()
	})
}

// StatusDie stamps the resource's status field with a mutable die.
func (d *FilteredRepositoryDie) StatusDie(fn func(d *FilteredRepositoryStatusDie)) *FilteredRepositoryDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepository) {
		d := FilteredRepositoryStatusBlank.DieImmutable(false).DieFeed(r.Status)
		fn(d)
		r.Status = d.DieRelease()
	})
}

func (d *FilteredRepositoryDie) Spec(v v1alpha1.FilteredRepositorySpec) *FilteredRepositoryDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepository) {
		r.Spec = v
	})
}

func (d *FilteredRepositoryDie) Status(v v1alpha1.FilteredRepositoryStatus) *FilteredRepositoryDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepository) {
		r.Status = v
	})
}

var FilteredRepositorySpecBlank = (&FilteredRepositorySpecDie{}).DieFeed(v1alpha1.FilteredRepositorySpec{})

type FilteredRepositorySpecDie struct {
	mutable bool
	r       v1alpha1.FilteredRepositorySpec
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *FilteredRepositorySpecDie) DieImmutable(immutable bool) *FilteredRepositorySpecDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *FilteredRepositorySpecDie) DieFeed(r v1alpha1.FilteredRepositorySpec) *FilteredRepositorySpecDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &FilteredRepositorySpecDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *FilteredRepositorySpecDie) DieFeedPtr(r *v1alpha1.FilteredRepositorySpec) *FilteredRepositorySpecDie {
	if r == nil {
		r = &v1alpha1.FilteredRepositorySpec{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *FilteredRepositorySpecDie) DieFeedJSON(j []byte) *FilteredRepositorySpecDie {
	r := v1alpha1.FilteredRepositorySpec{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *FilteredRepositorySpecDie) DieFeedYAML(y []byte) *FilteredRepositorySpecDie {
	r := v1alpha1.FilteredRepositorySpec{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *FilteredRepositorySpecDie) DieFeedYAMLFile(name string) *FilteredRepositorySpecDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *FilteredRepositorySpecDie) DieFeedRawExtension(raw runtime.RawExtension) *FilteredRepositorySpecDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *FilteredRepositorySpecDie) DieRelease() v1alpha1.FilteredRepositorySpec {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *FilteredRepositorySpecDie) DieReleasePtr() *v1alpha1.FilteredRepositorySpec {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *FilteredRepositorySpecDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *FilteredRepositorySpecDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *FilteredRepositorySpecDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *FilteredRepositorySpecDie) DieStamp(fn func(r *v1alpha1.FilteredRepositorySpec)) *FilteredRepositorySpecDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *FilteredRepositorySpecDie) DieStampAt(jp string, fn interface{}) *FilteredRepositorySpecDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepositorySpec) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *FilteredRepositorySpecDie) DeepCopy() *FilteredRepositorySpecDie {
	r := *d.r.DeepCopy()
	return &FilteredRepositorySpecDie{
		mutable: d.mutable,
		r:       r,
	}
}

func (d *FilteredRepositorySpecDie) SourceRef(v v1alpha1.SourceRef) *FilteredRepositorySpecDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepositorySpec) {
		r.SourceRef = v
	})
}

func (d *FilteredRepositorySpecDie) Include(v string) *FilteredRepositorySpecDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepositorySpec) {
		r.Include = v
	})
}

var FilteredRepositoryStatusBlank = (&FilteredRepositoryStatusDie{}).DieFeed(v1alpha1.FilteredRepositoryStatus{})

type FilteredRepositoryStatusDie struct {
	mutable bool
	r       v1alpha1.FilteredRepositoryStatus
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *FilteredRepositoryStatusDie) DieImmutable(immutable bool) *FilteredRepositoryStatusDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *FilteredRepositoryStatusDie) DieFeed(r v1alpha1.FilteredRepositoryStatus) *FilteredRepositoryStatusDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &FilteredRepositoryStatusDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *FilteredRepositoryStatusDie) DieFeedPtr(r *v1alpha1.FilteredRepositoryStatus) *FilteredRepositoryStatusDie {
	if r == nil {
		r = &v1alpha1.FilteredRepositoryStatus{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *FilteredRepositoryStatusDie) DieFeedJSON(j []byte) *FilteredRepositoryStatusDie {
	r := v1alpha1.FilteredRepositoryStatus{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *FilteredRepositoryStatusDie) DieFeedYAML(y []byte) *FilteredRepositoryStatusDie {
	r := v1alpha1.FilteredRepositoryStatus{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *FilteredRepositoryStatusDie) DieFeedYAMLFile(name string) *FilteredRepositoryStatusDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *FilteredRepositoryStatusDie) DieFeedRawExtension(raw runtime.RawExtension) *FilteredRepositoryStatusDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *FilteredRepositoryStatusDie) DieRelease() v1alpha1.FilteredRepositoryStatus {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *FilteredRepositoryStatusDie) DieReleasePtr() *v1alpha1.FilteredRepositoryStatus {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *FilteredRepositoryStatusDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *FilteredRepositoryStatusDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *FilteredRepositoryStatusDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *FilteredRepositoryStatusDie) DieStamp(fn func(r *v1alpha1.FilteredRepositoryStatus)) *FilteredRepositoryStatusDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *FilteredRepositoryStatusDie) DieStampAt(jp string, fn interface{}) *FilteredRepositoryStatusDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepositoryStatus) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *FilteredRepositoryStatusDie) DeepCopy() *FilteredRepositoryStatusDie {
	r := *d.r.DeepCopy()
	return &FilteredRepositoryStatusDie{
		mutable: d.mutable,
		r:       r,
	}
}

func (d *FilteredRepositoryStatusDie) Status(v apis.Status) *FilteredRepositoryStatusDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepositoryStatus) {
		r.Status = v
	})
}

// URL is the dynamic fetch link for the latest Artifact. It is provided on a "best effort" basis, and using the precise GitRepositoryStatus.Artifact data is recommended.
func (d *FilteredRepositoryStatusDie) URL(v string) *FilteredRepositoryStatusDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepositoryStatus) {
		r.URL = v
	})
}

// Artifact represents the last successful GitRepository reconciliation.
func (d *FilteredRepositoryStatusDie) Artifact(v *v1alpha1.Artifact) *FilteredRepositoryStatusDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepositoryStatus) {
		r.Artifact = v
	})
}

// ObservedInclude is the observed list of GitRepository resources used to calculate the checksum for this artifact
func (d *FilteredRepositoryStatusDie) ObservedInclude(v string) *FilteredRepositoryStatusDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepositoryStatus) {
		r.ObservedInclude = v
	})
}

// ObservedFileList is the file list used to calculate the checksum for this artifact
func (d *FilteredRepositoryStatusDie) ObservedFileList(v string) *FilteredRepositoryStatusDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepositoryStatus) {
		r.ObservedFileList = v
	})
}

func (d *FilteredRepositoryStatusDie) ReconcileRequestStatus(v meta.ReconcileRequestStatus) *FilteredRepositoryStatusDie {
	return d.DieStamp(func(r *v1alpha1.FilteredRepositoryStatus) {
		r.ReconcileRequestStatus = v
	})
}
